### ISSUE TITLE
[BUG] - Error during opening the image from ComfyUI

### ISSUE THREAD

**Issue by GlebIgorevich** [receyuki/stable-diffusion-prompt-reader#26] opened 2023-07-29 07:12 UTC
Some images opened correctly. Some images can't be opened, the tool shows error code only. Image with error is attached.
Prompt Reader v.1.3.2 win, Win 10 with latest patches

![изображение](https://github.com/receyuki/stable-diffusion-prompt-reader/assets/4972393/f8f01afd-e3c2-46e3-846f-e73c6bffafb2)

![refiner_continued_output_00464_](https://github.com/receyuki/stable-diffusion-prompt-reader/assets/4972393/28f8a2f0-f08b-4a68-afff-66307bf224df)

**Comment by receyuki** [comment] 2023-07-29 13:11
duplicate #25

**Comment by Marscog** [comment] 2023-08-11 20:02
I get the exact same error message.
![Marscog UI test_00736_](https://github.com/receyuki/stable-diffusion-prompt-reader/assets/142053317/81c36b2e-7ee1-4121-9885-5be46ad1f279)

**Comment by receyuki** [comment] 2023-08-12 09:52
The bug is caused by SDXL and will be fixed in the next update.

**Closed** 2023-09-03 16:20 UTC
Labels: duplicate
